import { z } from "zod";
import type { ExecutionNode } from "./security-domain.ts";

export const securityToolRiskLevels = ["passive", "external_passive", "active", "intrusive"] as const;
export const securityToolExecutionModes = ["typed_adapter", "not_enabled"] as const;

export const SecurityToolDefinitionSchema = z.object({
  id: z.string().trim().min(1),
  name: z.string().trim().min(1),
  executable: z.string().trim().min(1),
  category: z.string().trim().min(1),
  description: z.string().trim().min(1),
  versionArgs: z.array(z.string()),
  defaultRisk: z.enum(securityToolRiskLevels),
  networkAccess: z.boolean(),
  requiresPrivilege: z.boolean(),
  executionMode: z.enum(securityToolExecutionModes),
  operationIds: z.array(z.string().trim().min(1)),
  evidenceKinds: z.array(z.string().trim().min(1)).min(1),
});
export type SecurityToolDefinition = z.infer<typeof SecurityToolDefinitionSchema>;

export const SecurityToolStatusSchema = SecurityToolDefinitionSchema.extend({
  nodeId: z.string().min(1).nullable(),
  availability: z.enum(["available", "missing", "error", "unknown"]),
  version: z.string().nullable(),
  detail: z.string().nullable(),
  checkedAt: z.string().datetime().nullable(),
});
export type SecurityToolStatus = z.infer<typeof SecurityToolStatusSchema>;

function tool(input: SecurityToolDefinition): SecurityToolDefinition {
  return SecurityToolDefinitionSchema.parse(input);
}

export const defaultSecurityToolRegistry: readonly SecurityToolDefinition[] = [
  tool({ id: "dig", name: "DNS Utilities", executable: "dig", category: "dns", description: "Query public DNS records.", versionArgs: ["-v"], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["dns_lookup"], evidenceKinds: ["dns_records", "stdout", "stderr"] }),
  tool({ id: "nmap", name: "Nmap", executable: "nmap", category: "network", description: "Discover hosts and inventory network services.", versionArgs: ["--version"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["service_inventory"], evidenceKinds: ["network_services", "stdout", "stderr"] }),
  tool({ id: "whois", name: "Whois", executable: "whois", category: "osint", description: "Retrieve public registration records.", versionArgs: ["--version"], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["whois_lookup"], evidenceKinds: ["registration_records", "stdout", "stderr"] }),
  tool({ id: "dnsrecon", name: "DNSRecon", executable: "dnsrecon", category: "dns", description: "Collect standard public DNS and mail records.", versionArgs: ["-V"], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["domain_recon"], evidenceKinds: ["dns_records", "domains", "stdout", "stderr"] }),
  tool({ id: "curl", name: "curl", executable: "curl", category: "web", description: "Make HTTP requests and preserve response evidence.", versionArgs: ["--version"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["http_response", "stdout", "stderr"] }),
  tool({ id: "python3", name: "Python", executable: "python3", category: "utility", description: "Run reviewed local analysis scripts.", versionArgs: ["--version"], defaultRisk: "passive", networkAccess: false, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["artifact", "stdout", "stderr"] }),
  tool({ id: "git", name: "Git", executable: "git", category: "utility", description: "Inspect approved source repositories and history.", versionArgs: ["--version"], defaultRisk: "passive", networkAccess: false, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["repository_metadata", "stdout", "stderr"] }),
  tool({ id: "openssl", name: "OpenSSL", executable: "openssl", category: "crypto", description: "Inspect certificates, keys, and cryptographic material.", versionArgs: ["version"], defaultRisk: "passive", networkAccess: false, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["certificate_metadata", "stdout", "stderr"] }),
  tool({ id: "subfinder", name: "Subfinder", executable: "subfinder", category: "osint", description: "Discover public subdomain references.", versionArgs: ["-version"], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["domains", "stdout", "stderr"] }),
  tool({ id: "httpx", name: "HTTPX Python client", executable: "httpx", category: "web", description: "Installed binary is the general HTTP client, not ProjectDiscovery HTTPX; reconnaissance adaptation is blocked until the intended package is installed.", versionArgs: ["--help"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["http_response", "stdout", "stderr"] }),
  tool({ id: "amass", name: "Amass", executable: "amass", category: "osint", description: "Map public attack-surface relationships.", versionArgs: ["-version"], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["amass_passive_discovery"], evidenceKinds: ["domains", "relationships", "stdout", "stderr"] }),
  tool({ id: "theharvester", name: "theHarvester", executable: "theHarvester", category: "osint", description: "Collect public email, host, and domain references.", versionArgs: ["-h"], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["public_email_search"], evidenceKinds: ["identity_references", "domains", "stdout", "stderr"] }),
  tool({ id: "sherlock", name: "Sherlock", executable: "sherlock", category: "identity", description: "Check public username presence across supported sites.", versionArgs: ["--version"], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["public_username_search"], evidenceKinds: ["profile_references", "stdout", "stderr"] }),
  tool({ id: "maigret", name: "Maigret", executable: "maigret", category: "identity", description: "Collect public username profile references and metadata.", versionArgs: ["--version"], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["maigret_username_search", "maigret_full_username_search"], evidenceKinds: ["profile_references", "stdout", "stderr"] }),
  tool({ id: "holehe", name: "Holehe", executable: "holehe", category: "identity", description: "Check supported public account-registration clues for an authorized email.", versionArgs: ["--version"], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["email_account_search"], evidenceKinds: ["identity_references", "stdout", "stderr"] }),
  tool({ id: "phoneinfoga", name: "PhoneInfoga", executable: "phoneinfoga", category: "identity", description: "Normalize an authorized phone number and collect public-source pivots.", versionArgs: ["version"], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["phone_enrichment"], evidenceKinds: ["identity_references", "stdout", "stderr"] }),
  tool({ id: "whatweb", name: "WhatWeb", executable: "whatweb", category: "web", description: "Identify public web technologies.", versionArgs: ["--version"], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["web_fingerprint"], evidenceKinds: ["web_technologies", "stdout", "stderr"] }),
  tool({ id: "gobuster", name: "Gobuster", executable: "gobuster", category: "web", description: "Perform bounded content discovery against an approved URL.", versionArgs: ["version"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["web_content_discovery"], evidenceKinds: ["web_paths", "stdout", "stderr"] }),
  tool({ id: "spiderfoot", name: "SpiderFoot", executable: "spiderfoot", category: "osint", description: "Run modular public-source collection and relationship discovery.", versionArgs: ["--help"], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["identity_references", "relationships", "stdout", "stderr"] }),
  tool({ id: "recon-ng", name: "recon-ng", executable: "recon-ng", category: "osint", description: "Run reviewed public-source reconnaissance modules.", versionArgs: ["--version"], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["identity_references", "domains", "relationships", "stdout", "stderr"] }),
  tool({ id: "dnsenum", name: "dnsenum", executable: "dnsenum", category: "dns", description: "Enumerate public DNS records and names for an approved domain.", versionArgs: ["--help"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["dnsenum_discovery"], evidenceKinds: ["dns_records", "domains", "stdout", "stderr"] }),
  tool({ id: "dnsmap", name: "dnsmap", executable: "dnsmap", category: "dns", description: "Discover public subdomains using a bounded dictionary.", versionArgs: [], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["dnsmap_discovery"], evidenceKinds: ["domains", "stdout", "stderr"] }),
  tool({ id: "fierce", name: "Fierce", executable: "fierce", category: "dns", description: "Map public DNS names and address ranges for an approved domain.", versionArgs: ["--help"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["fierce_discovery"], evidenceKinds: ["domains", "ip_addresses", "stdout", "stderr"] }),
  tool({ id: "dmitry", name: "DMitry", executable: "dmitry", category: "osint", description: "Collect public host, registration, email, and subdomain information.", versionArgs: [], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["dmitry_domain_intel"], evidenceKinds: ["registration_records", "identity_references", "domains", "stdout", "stderr"] }),
  tool({ id: "arp-scan", name: "arp-scan", executable: "arp-scan", category: "network", description: "Discover devices on an explicitly authorized local CIDR.", versionArgs: ["--version"], defaultRisk: "active", networkAccess: true, requiresPrivilege: true, executionMode: "typed_adapter", operationIds: ["arp_scan_discovery"], evidenceKinds: ["network_hosts", "stdout", "stderr"] }),
  tool({ id: "fping", name: "fping", executable: "fping", category: "network", description: "Perform bounded reachability checks against authorized hosts or CIDRs.", versionArgs: ["-v"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["fping_reachability"], evidenceKinds: ["network_hosts", "stdout", "stderr"] }),
  tool({ id: "ike-scan", name: "ike-scan", executable: "ike-scan", category: "network", description: "Identify IKE services on an explicitly authorized host.", versionArgs: ["--version"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["ike_service_probe"], evidenceKinds: ["network_services", "stdout", "stderr"] }),
  tool({ id: "enum4linux", name: "enum4linux", executable: "enum4linux", category: "network", description: "Collect bounded SMB, policy, and Windows host information using a null session.", versionArgs: ["-h"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["enum4linux_host_audit"], evidenceKinds: ["network_services", "identity_references", "stdout", "stderr"] }),
  tool({ id: "smbclient", name: "smbclient", executable: "smbclient", category: "network", description: "List anonymously visible SMB shares on an explicitly authorized host.", versionArgs: ["--version"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["smb_anonymous_share_list"], evidenceKinds: ["network_services", "shares", "stdout", "stderr"] }),
  tool({ id: "smbmap", name: "SMBMap", executable: "smbmap", category: "network", description: "Map anonymous SMB share permissions without write checks.", versionArgs: ["--version"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["smbmap_anonymous"], evidenceKinds: ["shares", "permissions", "stdout", "stderr"] }),
  tool({ id: "snmpcheck", name: "snmpcheck system checker", executable: "snmpcheck", category: "utility", description: "Installed binary is a local system checker rather than an SNMP enumeration tool; network adaptation is blocked.", versionArgs: ["-h"], defaultRisk: "passive", networkAccess: false, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["stdout", "stderr"] }),
  tool({ id: "wafw00f", name: "Wafw00f", executable: "wafw00f", category: "web", description: "Identify web application firewalls on an approved URL.", versionArgs: ["--version"], defaultRisk: "external_passive", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["waf_detection"], evidenceKinds: ["web_technologies", "stdout", "stderr"] }),
  tool({ id: "sslscan", name: "sslscan", executable: "sslscan", category: "tls", description: "Inspect TLS protocols, certificates, and cipher support.", versionArgs: ["--version"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["sslscan_configuration"], evidenceKinds: ["certificate_metadata", "tls_configuration", "stdout", "stderr"] }),
  tool({ id: "sslyze", name: "SSLyze", executable: "sslyze", category: "tls", description: "Analyze TLS configuration for an approved endpoint.", versionArgs: ["--version"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["tls_configuration"], evidenceKinds: ["certificate_metadata", "tls_configuration", "stdout", "stderr"] }),
  tool({ id: "dirb", name: "DIRB", executable: "dirb", category: "web", description: "Perform bounded content discovery against an approved URL.", versionArgs: [], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["dirb_content_discovery"], evidenceKinds: ["web_paths", "stdout", "stderr"] }),
  tool({ id: "nikto", name: "Nikto", executable: "nikto", category: "web", description: "Run reviewed web-server configuration checks against an approved target.", versionArgs: ["-Version"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["nikto_web_audit"], evidenceKinds: ["web_observations", "stdout", "stderr"] }),
  tool({ id: "wpscan", name: "WPScan", executable: "wpscan", category: "web", description: "Assess an authorized WordPress site with passive detection and bounded requests.", versionArgs: ["--version"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["wpscan_audit"], evidenceKinds: ["web_observations", "vulnerability_observations", "stdout", "stderr"] }),
  tool({ id: "wapiti", name: "Wapiti", executable: "wapiti", category: "web", description: "Installed package is currently broken because its Python structlog dependency is missing.", versionArgs: ["--version"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["web_observations", "vulnerability_observations", "stdout", "stderr"] }),
  tool({ id: "wfuzz", name: "Wfuzz", executable: "wfuzz", category: "web", description: "Run reviewed and bounded web discovery payloads.", versionArgs: ["--version"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["wfuzz_content_discovery"], evidenceKinds: ["web_paths", "http_responses", "stdout", "stderr"] }),
  tool({ id: "exiftool", name: "ExifTool", executable: "exiftool", category: "forensics", description: "Extract structured metadata from an explicitly scoped file on the execution node.", versionArgs: ["-ver"], defaultRisk: "passive", networkAccess: false, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["exiftool_metadata"], evidenceKinds: ["file_metadata", "stdout", "stderr"] }),
  tool({ id: "yara", name: "YARA", executable: "yara", category: "forensics", description: "Match reviewed rules against authorized files.", versionArgs: ["--version"], defaultRisk: "passive", networkAccess: false, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["file_analysis", "stdout", "stderr"] }),
  tool({ id: "hashdeep", name: "hashdeep", executable: "hashdeep", category: "forensics", description: "Compute a SHA-256 hash for an explicitly scoped file.", versionArgs: ["-v"], defaultRisk: "passive", networkAccess: false, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["hashdeep_file_hash"], evidenceKinds: ["file_hashes", "stdout", "stderr"] }),
  tool({ id: "bulk-extractor", name: "bulk_extractor", executable: "bulk_extractor", category: "forensics", description: "Requires managed remote artifact directories and download cleanup before it can be enabled.", versionArgs: ["-V"], defaultRisk: "passive", networkAccess: false, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["file_analysis", "artifact", "stdout", "stderr"] }),
  tool({ id: "tsk_recover", name: "Sleuth Kit", executable: "tsk_recover", category: "forensics", description: "Recover files from an authorized forensic image.", versionArgs: ["-V"], defaultRisk: "passive", networkAccess: false, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["file_analysis", "artifact", "stdout", "stderr"] }),
  tool({ id: "searchsploit", name: "SearchSploit", executable: "searchsploit", category: "vulnerability", description: "Correlate an explicitly scoped software or CVE query with the local Exploit-DB index.", versionArgs: ["--help"], defaultRisk: "passive", networkAccess: false, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["searchsploit_lookup"], evidenceKinds: ["vulnerability_references", "stdout", "stderr"] }),
  tool({ id: "nuclei", name: "Nuclei", executable: "nuclei", category: "vulnerability", description: "Run approved template-based security checks.", versionArgs: ["-version"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["vulnerability_observations", "stdout", "stderr"] }),
  tool({ id: "ffuf", name: "ffuf", executable: "ffuf", category: "web", description: "Enumerate approved web content using bounded wordlists.", versionArgs: ["-V"], defaultRisk: "active", networkAccess: true, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["ffuf_content_discovery"], evidenceKinds: ["web_paths", "stdout", "stderr"] }),
  tool({ id: "sqlmap", name: "sqlmap", executable: "sqlmap", category: "vulnerability", description: "Validate suspected SQL injection within an authorized assessment.", versionArgs: ["--version"], defaultRisk: "intrusive", networkAccess: true, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["vulnerability_observations", "stdout", "stderr"] }),
  tool({ id: "hashcat", name: "Hashcat", executable: "hashcat", category: "password", description: "Audit user-provided password hashes offline.", versionArgs: ["--version"], defaultRisk: "intrusive", networkAccess: false, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["password_audit", "stdout", "stderr"] }),
  tool({ id: "john", name: "John the Ripper", executable: "john", category: "password", description: "Audit user-provided password material offline.", versionArgs: ["--list=build-info"], defaultRisk: "intrusive", networkAccess: false, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["password_audit", "stdout", "stderr"] }),
  tool({ id: "tshark", name: "TShark", executable: "tshark", category: "traffic", description: "Analyze up to 1,000 packets from an explicitly scoped capture file.", versionArgs: ["--version"], defaultRisk: "passive", networkAccess: false, requiresPrivilege: false, executionMode: "typed_adapter", operationIds: ["tshark_capture_analysis"], evidenceKinds: ["packet_analysis", "stdout", "stderr"] }),
  tool({ id: "tcpdump", name: "tcpdump", executable: "tcpdump", category: "traffic", description: "Capture authorized network traffic.", versionArgs: ["--version"], defaultRisk: "intrusive", networkAccess: true, requiresPrivilege: true, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["packet_capture", "stdout", "stderr"] }),
  tool({ id: "binwalk", name: "Binwalk", executable: "binwalk", category: "forensics", description: "Installed Binwalk package stalls even on a tiny local file and remains blocked pending package repair.", versionArgs: ["--version"], defaultRisk: "passive", networkAccess: false, requiresPrivilege: false, executionMode: "not_enabled", operationIds: [], evidenceKinds: ["binary_analysis", "artifact", "stdout", "stderr"] }),
] as const;

export function securityToolDefinitions(): SecurityToolDefinition[] {
  return defaultSecurityToolRegistry.map((definition) => ({ ...definition, versionArgs: [...definition.versionArgs], operationIds: [...definition.operationIds], evidenceKinds: [...definition.evidenceKinds] }));
}

export function securityToolStatuses(node?: ExecutionNode | null): SecurityToolStatus[] {
  const capabilities = new Map(node?.capabilities.map((capability) => [capability.id, capability]) ?? []);
  return securityToolDefinitions().map((definition) => {
    const capability = capabilities.get(definition.id);
    return SecurityToolStatusSchema.parse({
      ...definition,
      nodeId: node?.id ?? null,
      availability: capability?.status ?? "unknown",
      version: capability?.version ?? null,
      detail: capability?.detail ?? null,
      checkedAt: capability?.checkedAt ?? null,
    });
  });
}
