import type { TaskState } from "./contracts.ts";

const transitions: Record<TaskState, readonly TaskState[]> = {
  CREATED: ["CLASSIFYING", "PAUSED", "CANCELLED"],
  CLASSIFYING: ["DISCOVERING", "FAILED", "CANCELLED", "PAUSED", "RECOVERY_REQUIRED"],
  DISCOVERING: ["PLANNING", "FAILED", "CANCELLED", "PAUSED", "RECOVERY_REQUIRED"],
  PLANNING: ["AWAITING_APPROVAL", "IMPLEMENTING", "COMPLETE", "BLOCKED", "FAILED", "CANCELLED", "PAUSED", "RECOVERY_REQUIRED"],
  AWAITING_APPROVAL: ["IMPLEMENTING", "COMPLETE", "CANCELLED", "PAUSED", "RECOVERY_REQUIRED"],
  IMPLEMENTING: ["VERIFYING", "BLOCKED", "FAILED", "CANCELLED", "PAUSED", "RECOVERY_REQUIRED"],
  VERIFYING: ["IMPLEMENTING", "REVIEWING", "BLOCKED", "FAILED", "CANCELLED", "PAUSED", "RECOVERY_REQUIRED"],
  REVIEWING: ["IMPLEMENTING", "DELIVERY_READY", "BLOCKED", "FAILED", "CANCELLED", "PAUSED", "RECOVERY_REQUIRED"],
  DELIVERY_READY: ["REVIEWING", "DELIVERING", "CANCELLED", "PAUSED", "RECOVERY_REQUIRED"],
  DELIVERING: ["COMPLETE", "DELIVERY_READY", "FAILED", "CANCELLED", "PAUSED", "RECOVERY_REQUIRED"],
  PAUSED: ["CLASSIFYING", "DISCOVERING", "PLANNING", "AWAITING_APPROVAL", "IMPLEMENTING", "VERIFYING", "REVIEWING", "DELIVERY_READY", "DELIVERING", "RECOVERY_REQUIRED", "CANCELLED"],
  RECOVERY_REQUIRED: ["PLANNING", "PAUSED", "CANCELLED"],
  COMPLETE: [], BLOCKED: [], FAILED: [], CANCELLED: [],
};

export function canTransition(from: TaskState, to: TaskState): boolean { return transitions[from].includes(to); }
export function assertTransition(from: TaskState, to: TaskState): void { if (!canTransition(from, to)) throw new Error(`Invalid task transition: ${from} -> ${to}`); }
